const translations = {
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.investment": "Inversión",
    "nav.about": "Nosotros",
    "nav.contact": "Contacto",
    "cta.consultation": "Solicitar asesoría",
    "cta.services": "Conocer servicios",
    "hero.eyebrow": "Estrategias de inversión",
    "hero.title": "Estrategias de inversión para crecer tu patrimonio",
    "hero.subtitle": "Acompañamiento profesional para inversores que buscan rentabilidad, seguridad y decisiones inteligentes.",
    "hero.point1": "Asesoría privada",
    "hero.point2": "Oportunidades seleccionadas",
    "hero.point3": "Decisiones con criterio",
    "metric.market": "Mercado",
    "metric.return": "rendimiento anual",
    "chart.title": "Crecimiento",
    "panel.dashboard": "Panel de inversión",
    "panel.profile": "Perfil",
    "panel.profileValue": "Moderado",
    "panel.strategy": "Estrategia",
    "panel.strategyValue": "Activa",
    "metric1.label": "Rendimiento anual",
    "metric2.label": "Idiomas",
    "metric3.label": "Atención personalizada",
    "metric4.label": "Disponibilidad",
    "section.why": "¿Por qué elegirnos?",
    "benefits.title": "Soluciones creadas para inversores exigentes",
    "benefits.card1.title": "Experiencia",
    "benefits.card1.text": "Acompañamiento profesional con enfoque en oportunidades rentables y sostenibles.",
    "benefits.card2.title": "Confianza",
    "benefits.card2.text": "Enfoque serio, transparente y orientado a proteger el capital del inversor.",
    "benefits.card3.title": "Atención personalizada",
    "benefits.card3.text": "Cada estrategia se adapta a tu perfil, objetivos y nivel de riesgo.",
    "benefits.card4.title": "Oportunidades",
    "benefits.card4.text": "Acceso a propuestas relevantes para generar valor en el largo plazo.",
    "section.services": "Servicios",
    "services.title": "Asesoría adaptada a tus objetivos",
    "services.card1.title": "Asesoría inmobiliaria",
    "services.card1.text": "Identificamos oportunidades atractivas según tu perfil y tus objetivos financieros.",
    "services.card2.title": "Inversión estratégica",
    "services.card2.text": "Analizamos posibles rutas de inversión para lograr rentabilidad con criterio.",
    "services.card3.title": "Captación de inversores",
    "services.card3.text": "Conectamos perfiles con oportunidades que encajen con su capacidad de inversión.",
    "section.investment": "Inversión",
    "investment.title": "Un enfoque claro para maximizar oportunidades",
    "investment.text": "La inversión exige criterio, análisis y visión de largo plazo. En AndradeProperty te ayudamos a visualizar alternativas con sentido estratégico.",
    "investment.item1": "Diagnóstico inicial personalizado",
    "investment.item2": "Evaluación de perfil y riesgo",
    "investment.item3": "Recomendación estructurada",
    "investment.item4": "Asesoría de continuidad",
    "step1.title": "Diagnóstico",
    "step1.text": "Conocemos tus metas, perfil y expectativas.",
    "step2.title": "Perfil",
    "step2.text": "Definimos riesgos, horizonte y capacidad de inversión.",
    "step3.title": "Recomendación",
    "step3.text": "Te proponemos opciones estratégicas y bien orientadas.",
    "step4.title": "Seguimiento",
    "step4.text": "Te acompañamos durante el proceso con criterio continuo.",
    "section.about": "Nosotros",
    "about.title": "Especialistas en conectar inversión y oportunidad",
    "about.text1": "Somos un equipo orientado a la relación profesional con inversores, ofreciendo análisis, acompañamiento y acceso a oportunidades del mercado.",
    "about.text2": "Nuestra misión es generar confianza, claridad y decisión financiera con una visión moderna y estratégica.",
    "section.testimonials": "Testimonios",
    "testimonials.title": "Opiniones de clientes y socios",
    "quote1": "“Muy profesional, claro y serio. Me ayudó a entender mejor dónde tomar decisiones con criterio.”",
    "quote2": "“Atención muy personalizada. La estrategia quedó mucho más clara y orientada a mis objetivos.”",
    "quote3": "“La visión fue muy útil para tomar decisiones con mayor confianza y mejor criterio.”",
    "section.contact": "Contacto",
    "contact.title": "Agenda una consulta privada",
    "contact.subtitle": "Cuéntanos tus objetivos y te ayudaremos a evaluar oportunidades relevantes.",
    "form.name": "Nombre",
    "form.email": "Email",
    "form.phone": "Teléfono",
    "form.country": "País",
    "form.investment": "Monto aproximado de inversión",
    "form.message": "Mensaje",
    "form.submit": "Enviar consulta",
    "footer.text": "Asesoría para inversores que buscan oportunidades reales, rentables y bien orientadas.",
    "footer.links": "Enlaces",
    "footer.contact": "Contacto"
  },
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.investment": "Investment",
    "nav.about": "About us",
    "nav.contact": "Contact",
    "cta.consultation": "Request consultation",
    "cta.services": "View services",
    "hero.eyebrow": "Investment strategies",
    "hero.title": "Investment strategies to grow your wealth",
    "hero.subtitle": "Professional guidance for investors seeking profitability, security and intelligent decisions.",
    "hero.point1": "Private advisory",
    "hero.point2": "Selected opportunities",
    "hero.point3": "Decision with criteria",
    "metric.market": "Market",
    "metric.return": "annual return",
    "chart.title": "Growth",
    "panel.dashboard": "Investment panel",
    "panel.profile": "Profile",
    "panel.profileValue": "Moderate",
    "panel.strategy": "Strategy",
    "panel.strategyValue": "Active",
    "metric1.label": "Annual return",
    "metric2.label": "Languages",
    "metric3.label": "Personalized attention",
    "metric4.label": "Availability",
    "section.why": "Why choose us?",
    "benefits.title": "Solutions designed for demanding investors",
    "benefits.card1.title": "Experience",
    "benefits.card1.text": "Professional guidance focused on profitable and sustainable opportunities.",
    "benefits.card2.title": "Trust",
    "benefits.card2.text": "Serious, transparent approach aimed at protecting the investor's capital.",
    "benefits.card3.title": "Personalized attention",
    "benefits.card3.text": "Each strategy is tailored to your profile, goals and risk level.",
    "benefits.card4.title": "Opportunities",
    "benefits.card4.text": "Access to relevant proposals designed to generate long-term value.",
    "section.services": "Services",
    "services.title": "Advice tailored to your goals",
    "services.card1.title": "Real estate advisory",
    "services.card1.text": "We identify attractive opportunities based on your profile and financial goals.",
    "services.card2.title": "Strategic investment",
    "services.card2.text": "We analyze possible investment paths to achieve profitability with criteria.",
    "services.card3.title": "Investor acquisition",
    "services.card3.text": "We connect investors with opportunities that match their investment capacity.",
    "section.investment": "Investment",
    "investment.title": "A clear approach to maximize opportunities",
    "investment.text": "Investment requires criteria, analysis and long-term vision. At AndradeProperty we help you evaluate alternatives with strategic sense.",
    "investment.item1": "Initial personalized diagnosis",
    "investment.item2": "Risk and profile assessment",
    "investment.item3": "Structured recommendation",
    "investment.item4": "Ongoing advisory",
    "step1.title": "Diagnosis",
    "step1.text": "We understand your goals, profile and expectations.",
    "step2.title": "Profile",
    "step2.text": "We define risk, timeline and investment capacity.",
    "step3.title": "Recommendation",
    "step3.text": "We propose strategic and well-oriented options.",
    "step4.title": "Monitoring",
    "step4.text": "We guide you through the process with continuous criteria.",
    "section.about": "About us",
    "about.title": "Specialists in connecting investment and opportunity",
    "about.text1": "We are a team focused on the professional relationship with investors, offering analysis, accompaniment and access to market opportunities.",
    "about.text2": "Our mission is to generate trust, clarity and financial decision-making with a modern and strategic vision.",
    "section.testimonials": "Testimonials",
    "testimonials.title": "Customer and partner feedback",
    "quote1": "“Very professional, clear and serious. It helped me understand better where to make decisions with criteria.”",
    "quote2": "“Very personalized attention. The strategy became much clearer and more aligned with my goals.”",
    "quote3": "“The vision was very useful for making decisions with more confidence and better judgment.”",
    "section.contact": "Contact",
    "contact.title": "Schedule a private consultation",
    "contact.subtitle": "Tell us your goals and we will help you evaluate relevant opportunities.",
    "form.name": "Name",
    "form.email": "Email",
    "form.phone": "Phone",
    "form.country": "Country",
    "form.investment": "Approximate investment amount",
    "form.message": "Message",
    "form.submit": "Send consultation",
    "footer.text": "Advice for investors looking for real, profitable and well-oriented opportunities.",
    "footer.links": "Links",
    "footer.contact": "Contact"
  },
  zh: {
    "nav.home": "首页",
    "nav.services": "服务",
    "nav.investment": "投资",
    "nav.about": "关于我们",
    "nav.contact": "联系我们",
    "cta.consultation": "申请咨询",
    "cta.services": "查看服务",
    "hero.eyebrow": "投资策略",
    "hero.title": "助力您财富增长的投资策略",
    "hero.subtitle": "为寻求收益、安全和明智决策的投资者提供专业指导。",
    "hero.point1": "私人咨询",
    "hero.point2": "精选机会",
    "hero.point3": "基于判断的决策",
    "metric.market": "市场",
    "metric.return": "年回报率",
    "chart.title": "增长",
    "panel.dashboard": "投资面板",
    "panel.profile": "风险偏好",
    "panel.profileValue": "中等",
    "panel.strategy": "策略",
    "panel.strategyValue": "活跃",
    "metric1.label": "年回报率",
    "metric2.label": "语言",
    "metric3.label": "个性化服务",
    "metric4.label": "可用性",
    "section.why": "为什么选择我们？",
    "benefits.title": "专为高要求投资者设计的解决方案",
    "benefits.card1.title": "经验",
    "benefits.card1.text": "以可持续和高收益机会为重点的专业支持。",
    "benefits.card2.title": "信任",
    "benefits.card2.text": "严谨、透明、以保护投资者资本为核心的方式。",
    "benefits.card3.title": "个性化服务",
    "benefits.card3.text": "每项策略都根据您的个人情况、目标和风险承受能力量身定制。",
    "benefits.card4.title": "机会",
    "benefits.card4.text": "获取适合长期创造价值的相关机会。",
    "section.services": "服务",
    "services.title": "根据您的目标量身定制咨询",
    "services.card1.title": "房地产咨询",
    "services.card1.text": "根据您的财务目标和风险偏好，识别具有吸引力的机会。",
    "services.card2.title": "战略投资",
    "services.card2.text": "分析可能的投资路径，以更稳健的方式实现收益。",
    "services.card3.title": "投资者匹配",
    "services.card3.text": "将投资者与符合其投资能力的机会连接起来。",
    "section.investment": "投资",
    "investment.title": "以清晰思路最大化机会",
    "investment.text": "投资需要标准、分析和长期视角。在 AndradeProperty，我们帮助您从战略角度评估可行选择。",
    "investment.item1": "个性化初步诊断",
    "investment.item2": "风险和画像评估",
    "investment.item3": "结构化建议",
    "investment.item4": "持续咨询",
    "step1.title": "诊断",
    "step1.text": "我们了解您的目标、画像和预期。",
    "step2.title": "画像",
    "step2.text": "我们明确风险、时间范围和投资能力。",
    "step3.title": "建议",
    "step3.text": "为您提出策略性且明确的方案。",
    "step4.title": "跟踪",
    "step4.text": "我们持续陪伴您并提供持续判断支持。",
    "section.about": "关于我们",
    "about.title": "连接投资与机会的专业团队",
    "about.text1": "我们专注于与投资者的专业关系，提供分析、陪伴和市场机会的接入。",
    "about.text2": "我们的使命是在现代化和战略化的视角下，创造信任、清晰与金融决策能力。",
    "section.testimonials": "评价",
    "testimonials.title": "客户和合作伙伴的反馈",
    "quote1": "“专业、清晰、认真。它帮助我更好地理解在哪里做出更有判断力的决策。”",
    "quote2": "“非常个性化的服务。策略更加清晰，也更符合我的目标。”",
    "quote3": "“这个视角对我更有信心地做出决策非常有帮助。”",
    "section.contact": "联系我们",
    "contact.title": "预约私人咨询",
    "contact.subtitle": "告诉我们您的目标，我们将帮助您评估相关机会。",
    "form.name": "姓名",
    "form.email": "电子邮件",
    "form.phone": "电话",
    "form.country": "国家",
    "form.investment": "大致投资金额",
    "form.message": "留言",
    "form.submit": "发送咨询",
    "footer.text": "为寻求真实、盈利且方向明确的机会的投资者提供咨询。",
    "footer.links": "链接",
    "footer.contact": "联系信息"
  },
  ru: {
    "nav.home": "Главная",
    "nav.services": "Услуги",
    "nav.investment": "Инвестиции",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "cta.consultation": "Запросить консультацию",
    "cta.services": "Посмотреть услуги",
    "hero.eyebrow": "Инвестиционные стратегии",
    "hero.title": "Инвестиционные стратегии для роста вашего капитала",
    "hero.subtitle": "Профессиональное сопровождение для инвесторов, ищущих прибыльность, безопасность и разумные решения.",
    "hero.point1": "Частная консультация",
    "hero.point2": "Отобранные возможности",
    "hero.point3": "Решения с учетом критериев",
    "metric.market": "Рынок",
    "metric.return": "годовая доходность",
    "chart.title": "Рост",
    "panel.dashboard": "Инвестиционная панель",
    "panel.profile": "Профиль",
    "panel.profileValue": "Средний",
    "panel.strategy": "Стратегия",
    "panel.strategyValue": "Активная",
    "metric1.label": "Годовая доходность",
    "metric2.label": "Языки",
    "metric3.label": "Персональное внимание",
    "metric4.label": "Доступность",
    "section.why": "Почему нас выбирают?",
    "benefits.title": "Решения, рассчитанные на требовательных инвесторов",
    "benefits.card1.title": "Опыт",
    "benefits.card1.text": "Профессиональное сопровождение с упором на прибыльные и устойчивые возможности.",
    "benefits.card2.title": "Доверие",
    "benefits.card2.text": "Серьезный, прозрачный подход, ориентированный на защиту капитала инвестора.",
    "benefits.card3.title": "Персональное внимание",
    "benefits.card3.text": "Каждая стратегия адаптируется под ваш профиль, цели и уровень риска.",
    "benefits.card4.title": "Возможности",
    "benefits.card4.text": "Доступ к релевантным предложениям, направленным на долгосрочную ценность.",
    "section.services": "Услуги",
    "services.title": "Консультации под ваши цели",
    "services.card1.title": "Недвижимость-консалтинг",
    "services.card1.text": "Мы выявляем привлекательные возможности исходя из вашего профиля и финансовых целей.",
    "services.card2.title": "Стратегические инвестиции",
    "services.card2.text": "Мы анализируем возможные варианты инвестирования для достижения доходности с учетом критериев.",
    "services.card3.title": "Привлечение инвесторов",
    "services.card3.text": "Мы соединяем профили с возможностями, соответствующими их инвестиционным возможностям.",
    "section.investment": "Инвестиции",
    "investment.title": "Четкий подход для максимизации возможностей",
    "investment.text": "Инвестиции требуют критериев, анализа и долгосрочного взгляда. В AndradeProperty мы помогаем оценить альтернативы с точки зрения стратегии.",
    "investment.item1": "Индивидуальная первичная диагностика",
    "investment.item2": "Оценка профиля и риска",
    "investment.item3": "Структурированная рекомендация",
    "investment.item4": "Постоянная консультация",
    "step1.title": "Диагностика",
    "step1.text": "Мы понимаем ваши цели, профиль и ожидания.",
    "step2.title": "Профиль",
    "step2.text": "Мы определяем риск, горизонт и инвестиционные возможности.",
    "step3.title": "Рекомендация",
    "step3.text": "Мы предлагаем стратегические и хорошо ориентированные варианты.",
    "step4.title": "Мониторинг",
    "step4.text": "Мы сопровождаем вас в процессе с постоянной аналитикой.",
    "section.about": "О нас",
    "about.title": "Специалисты в соединении инвестиций и возможностей",
    "about.text1": "Мы — команда, ориентированная на профессиональные отношения с инвесторами, предлагая анализ, сопровождение и доступ к рыночным возможностям.",
    "about.text2": "Наша миссия — создавать доверие, ясность и принятие финансовых решений на основе современной стратегической логики.",
    "section.testimonials": "Отзывы",
    "testimonials.title": "Отзывы клиентов и партнеров",
    "quote1": "“Очень профессионально, ясно и серьезно. Это помогло лучше понять, где принимать решения с учетом критериев.”",
    "quote2": "“Очень персонализированное внимание. Стратегия стала гораздо понятнее и лучше соответствовала моим целям.”",
    "quote3": "“Этот взгляд был очень полезен для принятия решений с большей уверенностью и лучшим суждением.”",
    "section.contact": "Контакты",
    "contact.title": "Запишитесь на частную консультацию",
    "contact.subtitle": "Расскажите о своих целях, и мы поможем оценить подходящие возможности.",
    "form.name": "Имя",
    "form.email": "Электронная почта",
    "form.phone": "Телефон",
    "form.country": "Страна",
    "form.investment": "Примерная сумма инвестиций",
    "form.message": "Сообщение",
    "form.submit": "Отправить запрос",
    "footer.text": "Консультации для инвесторов, ищущих реальные, прибыльные и хорошо ориентированные возможности.",
    "footer.links": "Ссылки",
    "footer.contact": "Контакты"
  }
};

const elements = document.querySelectorAll("[data-i18n]");
const langButtons = document.querySelectorAll(".lang-btn");

function applyLanguage(lang) {
  const dict = translations[lang] || translations.es;

  elements.forEach((element) => {
    const key = element.dataset.i18n;
    if (dict[key]) {
      element.textContent = dict[key];
    }
  });

  langButtons.forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });

  document.documentElement.lang = lang;
}

langButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage("es");
